---
- name: Install rpmfusion repositories
  become: yes
  dnf:
    name: [
      "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm",
      "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm",
    ]
    state: present
    disable_gpg_check: yes
  tags:
    - basic_update
    - install_rpmfusion_repositories

- name: Update packages
  become: yes
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  tags:
    - basic_update
    - update_packages
