---
- name: Install flathub flatpak repo
  become: yes
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: system
  tags:
    - install_flathub_repo
    - flatpak

- name: Install Arc GTK theme for flatpak apps
  become: yes
  flatpak:
    name: org.gtk.Gtk3theme.Arc
    state: present
    method: system
  tags:
    - install_arc_gtk_theme_flatpak
    - flatpak
