---
- name: Configure grub (timeout style)
  become: yes
  lineinfile:
    path: /etc/default/grub
    state: present
    regexp: '^GRUB_TIMEOUT_STYLE\='
    line: "GRUB_TIMEOUT_STYLE=hidden"
  notify: dump grub config
  tags:
    - configure_grub

- name: Configure grub (timeout)
  become: yes
  lineinfile:
    path: /etc/default/grub
    state: present
    regexp: '^GRUB_TIMEOUT\='
    line: "GRUB_TIMEOUT=0"
  notify: dump grub config
  tags:
    - configure_grub
