---
- name: Configure grub (timeout style)
  become: yes
  lineinfile:
    path: /etc/default/grub
    state: present
    regexp: '^GRUB_TIMEOUT_STYLE\='
    line: "GRUB_TIMEOUT_STYLE={{ grub_timeout_style | default('menu') }}"
  notify: dump grub config
  tags:
    - configure_grub

- name: Configure grub (timeout)
  become: yes
  lineinfile:
    path: /etc/default/grub
    state: present
    regexp: '^GRUB_TIMEOUT\='
    line: "GRUB_TIMEOUT={{ grub_timeout | default('10') }}"
  notify: dump grub config
  tags:
    - configure_grub
