---
- name: Configure swappiness (1)
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    create: yes
    state: present
    regexp: '^vm\.swappiness\='
    line: "vm.swappiness={{ swappiness | default(10) }}"
  tags:
    - configure_swappiness

# @see https://success.docker.com/article/node-using-swap-memory-instead-of-host-memory
- name: Configure swappiness (2)
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    create: yes
    state: present
    regexp: '^vm\.overcommit_memory\='
    line: "vm.overcommit_memory=1"
  tags:
    - configure_swappiness
