---
- name: Check if nvim plugin manager is already installed
  stat:
    path: ~/.local/share/nvim/site/autoload/plug.vim
  register: plug
  when: "'neovim' in cli_tools | default([])"
  tags:
    - configure_nvim

- name: Create nvim plugin manager directory
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory
  when: "'neovim' in cli_tools | default([]) and plug.stat.exists == False"
  tags:
    - configure_nvim

- name: Install nvim plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
  when: "'neovim' in cli_tools | default([]) and plug.stat.exists == False"
  tags:
    - configure_nvim
