---
- name: Install flathub flatpak repo
  become: yes
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: system
  tags:
    - install_flathub_repo
    - flatpak
