---
- name: Disable unneeded services
  become: yes
  ignore_errors: yes
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    masked: yes
  with_items: "{{ services_to_disable | default([]) }}"
  tags:
    - disable_unneeded_services
