---
- name: Find tracker miner systemd user services
  find:
    path: /usr/lib/systemd/user
    patterns: "tracker-*.service"
  register: tracker_miner_services
  tags:
    - disable_tracker_miner

# see https://www.linuxuprising.com/2019/07/how-to-completely-disable-tracker.html
- name: Disable tracker miner (systemd user services)
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    masked: yes
    scope: user
  with_items: "{{ tracker_miner_services.files | map(attribute='path') | map('basename') | list }}"
  tags:
    - disable_tracker_miner
