---
# @see https://rudd-o.com/linux-and-free-software/how-to-use-your-xbox-368-controllers-under-fedora
- name: Install joystick package and kernel module
  become: yes
  dnf:
    name: [
      "kernel-modules-extra",
    ]
    state: present
  when: enable_xbox_controller
  tags:
    - enable_xbox_controller_kernel_module

- name: Enable xpad kernel module
  become: yes
  modprobe:
    name: xpad
    state: present
  when: enable_xbox_controller
  tags:
    - enable_xbox_controller_kernel_module
