---
# @see https://blog.jallet.org/controler-le-retro-eclairage-du-clevo-n151zu-1178.html
# @see https://github.com/tuxedocomputers/tuxedo-keyboard
- name: Install required packages to install tuxedo kernel module
  become: yes
  dnf:
    name: [
      "dkms",
      "kernel-devel",
    ]
    state: present
  when: enable_tuxedo_keyboard_backlight_controls
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Copy tuxedo configuration
  become: yes
  template:
    src: ../templates/tuxedo-keyboard/module.conf.j2
    dest: /etc/modprobe.d/tuxedo_keyboard.conf
    mode: 0644
    owner: root
    group: root
  when: enable_tuxedo_keyboard_backlight_controls
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Clone tuxedo repo
  become: yes
  git:
    repo: https://github.com/tuxedocomputers/tuxedo-keyboard.git
    dest: "/usr/src/tuxedo_keyboard-{{ tuxedo_keyboard_version }}"
    clone: yes
    version: "{{ tuxedo_keyboard_commit }}"
  register: tuxedo_cloned
  when: enable_tuxedo_keyboard_backlight_controls
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Install tuxedo kernel module (step 1/2)
  become: yes
  make:
    chdir: "/usr/src/tuxedo_keyboard-{{ tuxedo_keyboard_version }}"
    target: clean
  when: enable_tuxedo_keyboard_backlight_controls and tuxedo_cloned is changed
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Install tuxedo kernel module (step 2/2)
  become: yes
  make:
    chdir: "/usr/src/tuxedo_keyboard-{{ tuxedo_keyboard_version }}"
    target: dkmsinstall
  when: enable_tuxedo_keyboard_backlight_controls and tuxedo_cloned is changed
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Enable tuxedo kernel module
  become: yes
  modprobe:
    name: tuxedo_keyboard
    state: present
  when: enable_tuxedo_keyboard_backlight_controls and tuxedo_cloned is changed
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Load tuxedo kernel module on boot
  become: yes
  template:
    src: ../templates/tuxedo-keyboard/load.conf.j2
    dest: /etc/modules-load.d/tuxedo_keyboard.conf
    mode: 0644
    owner: root
    group: root
  when: enable_tuxedo_keyboard_backlight_controls and tuxedo_cloned is changed
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: State tuxedo sources directory
  stat:
    path: "/usr/src/tuxedo_keyboard-{{ tuxedo_keyboard_version }}"
  register: src_dir
  when: not enable_tuxedo_keyboard_backlight_controls
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Uninstall tuxedo dkms module
  become: yes
  make:
    chdir: "/usr/src/tuxedo_keyboard-{{ tuxedo_keyboard_version }}"
    target: dkmsremove
  when: not enable_tuxedo_keyboard_backlight_controls and src_dir.stat.isdir is defined and src_dir.stat.isdir
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Remove tuxedo sources dir and config files
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/usr/src/tuxedo_keyboard-{{ tuxedo_keyboard_version }}"
    - /etc/modules-load.d/tuxedo_keyboard.conf
    - /etc/modprobe.d/tuxedo_keyboard.conf
  when: not enable_tuxedo_keyboard_backlight_controls
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module
