---
# @see https://blog.jallet.org/controler-le-retro-eclairage-du-clevo-n151zu-1178.html
# @see https://github.com/tuxedocomputers/tuxedo-keyboard
- name: Install required packages to install tuxedo kernel module
  become: yes
  dnf:
    name: [
      "dkms",
      "kernel-devel",
    ]
    state: present
  when: enable_tuxedo_keyboard_backlight_controls
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Copy tuxedo configuration
  become: yes
  template:
    src: ../templates/tuxedo-keyboard/module.conf.j2
    dest: /etc/modprobe.d/tuxedo_keyboard.conf
    mode: 0644
    owner: root
    group: root
  when: enable_tuxedo_keyboard_backlight_controls
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Delete tuxedo sources
  become: yes
  file:
    path: "/usr/src/tuxedo_keyboard-{{ tuxedo_keyboard_version }}"
    state: absent
  when: enable_tuxedo_keyboard_backlight_controls and force_tuxedo_keyboard_backlight_controls_reinstall
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Remove previously installed tuxedo_keyboard kernel module
  become: yes
  ignore_errors: yes
  command: "dkms remove -m tuxedo_keyboard -v {{ tuxedo_keyboard_version }} --all"
  args:
    warn: no
  when: enable_tuxedo_keyboard_backlight_controls and force_tuxedo_keyboard_backlight_controls_reinstall
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Clone tuxedo repo
  become: yes
  git:
    repo: https://github.com/tuxedocomputers/tuxedo-keyboard.git
    dest: "/usr/src/tuxedo_keyboard-{{ tuxedo_keyboard_version }}"
    clone: yes
    version: "{{ tuxedo_keyboard_commit }}"
  register: tuxedo_cloned
  when: enable_tuxedo_keyboard_backlight_controls
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Add tuxedo kernel module
  become: yes
  ignore_errors: yes
  command: "dkms add -m tuxedo_keyboard -v {{ tuxedo_keyboard_version }}"
  args:
    warn: no
  when: enable_tuxedo_keyboard_backlight_controls and tuxedo_cloned is changed
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Install tuxedo kernel module
  become: yes
  command: "dkms install -m tuxedo_keyboard -v {{ tuxedo_keyboard_version }}"
  args:
    warn: no
  when: enable_tuxedo_keyboard_backlight_controls and tuxedo_cloned is changed
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Enable tuxedo kernel module
  become: yes
  modprobe:
    name: tuxedo_keyboard
    state: present
  when: enable_tuxedo_keyboard_backlight_controls and tuxedo_cloned is changed
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module

- name: Load tuxedo kernel module on boot
  become: yes
  template:
    src: ../templates/tuxedo-keyboard/load.conf.j2
    dest: /etc/modules-load.d/tuxedo_keyboard.conf
    mode: 0644
    owner: root
    group: root
  when: enable_tuxedo_keyboard_backlight_controls and tuxedo_cloned is changed
  tags:
    - enable_tuxedo_keyboard_backlight_kernel_module
