---
- name: Install CLI tools
  become: yes
  dnf:
    name: "{{ cli_tools | default([]) }}"
    state: present
    allowerasing: true
  tags:
    - install_cli_tools

- name: Install yq
  become: yes
  pip:
    name: yq
  when: install_yq | default(false)
  tags:
    - install_cli_tools
    - install_yq
