---
# Install mixxx via flatpak as they provide stable releases.
# Installing via dnf (which uses RPM fusion repos), can provide unstable (beta)
# releases.
- name: Install mixxx
  become: yes
  flatpak:
    name: org.mixxx.Mixxx
    state: present
    method: system
  when: install_mixxx | default(false)
  tags:
    - install_mixxx
    - flatpak
