---
- name: Install rustup (will install rust and cargo for the current user)
  shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
  args:
    warn: no
  when: install_rust
  tags:
    - install_rust

- name: Install rust LSP
  shell: "~/.cargo/bin/rustup +nightly component add rust-analyzer-preview"
  args:
    warn: no
  when: install_rust
  tags:
    - install_rust
