---
# the docker-ce package is now shipped by moby-engine package on fedora
# see https://github.com/docker/for-linux/issues/600#issuecomment-495894108
- name: Install docker
  become: yes
  dnf:
    name: [
      "docker-compose",
      "moby-engine",
    ]
    state: present
  tags:
    - install_docker

- name: Create docker group
  become: yes
  group:
    name: docker
    state: present
  tags:
    - install_docker

- name: Join docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags:
    - install_docker

- name: Enable docker service
  become: yes
  systemd:
    name: docker
    enabled: yes
  tags:
    - install_docker

# Set custom config for the docker daemon installed with moby-engine package.
#
# Default opts : OPTIONS='--selinux-enabled --log-driver=journald --live-restore'
# Set a limit for the number of opened files ( https://bugzilla.redhat.com/show_bug.cgi?id=1715254 )
# Remove the --live-restore option to be able to run docker in swarm mode.
#
# See the default config file at https://src.fedoraproject.org/rpms/moby-engine/blob/master/f/docker.sysconfig
- name: Copy docker options configuration
  become: yes
  copy:
    src: etc/sysconfig/docker
    dest: /etc/sysconfig/docker
  notify: restart docker
  tags:
    - install_docker
    - copy_docker_options

# @see https://ask.fedoraproject.org/t/dns-resolution-errors-with-docker-in-fedora-32/6385/3
# @see https://fedoraproject.org/wiki/Common_F32_bugs#mDNS_.28multicast_DNS.29_breaks_on_upgrade_to_Fedora_32
- name: Configure container DNS resolution
  become: yes
  lineinfile:
    path: /etc/nsswitch.conf
    create: yes
    state: present
    regexp: '^hosts\:'
    line: "hosts:      files dns myhostname"
  notify: restart docker
  tags:
    - install_docker
    - configure_container_dns

# As Fedora 32 has moved firewalld backend to nftables by default (since the
# use of firewalld > v0.6), we should revert it to iptables backend as it's the
# only thing that docker supports. Otherwise, containers in the same network
# won't be able to reach each other.
#
# @see https://fedoraproject.org/wiki/Changes/firewalld_default_to_nftables
# @see https://freesteph.info/blog/fedora-32-docker-compose.html
# @see https://pastebin.com/Zq3Gev7w
- name: Revert firewalld backend to iptables
  become: yes
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    create: yes
    state: present
    regexp: '^FirewallBackend\='
    line: "FirewallBackend=iptables"
  notify: restart firewalld
  tags:
    - install_docker
    - configure_firewalld
