---
- name: Install graphical apps
  become: yes
  dnf:
    name: [
      "audacity",
      "chromium",
      "chromium-common",
      "chromium-libs",
      "chromium-libs-media",
      "chromium-libs-media-freeworld",
      "clementine",
      "easytag",
      "gimp",
      "gucharmap",
      "gparted",
      "firefox",
      "fontforge",
      "inkscape",
      "libreoffice",
      "mediawriter",
      "playonlinux",
      "steam",
      "thunderbird",
      "thunderbird-enigmail",
      "vlc",
      "tilix",
      "transmission-gtk",
      "wine",
      "wireshark",
    ]
    state: present
  tags:
    - install_graphical_apps

- name: Join wireshark group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: wireshark
    append: yes
  tags:
    - install_graphical_apps
