---
- name: Install CLI tools
  become: yes
  dnf:
    name: [
      "curl",
      "dnf-plugins-core",
      "gcc",
      "git",
      "jq",
      "make",
      "neofetch",
      "neovim",
      "nethogs",
      "nmap",
      "powerline",
      "python3",
      "python3-devel",
      "python3-neovim",
      "redhat-rpm-config",
      "ruby",
      "ruby-devel",
      "ShellCheck",
      "tig",
      "unrar",
      "util-linux-user",
      "vagrant",
      "vim",
      "vim-enhanced",
      "wget",
    ]
    state: present
  tags:
    - install_cli_tools

- name: Install yq
  become: yes
  get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ yq_version }}/yq_linux_amd64"
    dest: /usr/local/bin/yq
    mode: 0755
  vars:
    - yq_version: 2.4.0
  tags:
    - install_cli_tools
    - install_yq
