---
- name: Check if git-standup is already installed
  stat:
    path: /usr/local/bin/git-standup
  register: git_standup
  tags:
    - install_git_standup

- name: Download git-standup install script
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/kamranahmedse/git-standup/master/installer.sh
    dest: /tmp/git-standup-installer.sh
    mode: 700
  when: git_standup.stat.exists == False
  tags:
    - install_git_standup

- name: Install git-standup
  become: yes
  shell: /tmp/git-standup-installer.sh
  when: git_standup.stat.exists == False
  tags:
    - install_git_standup

- name: Remove git-standup installation script
  file:
    path: /tmp/git-standup-installer.sh
    state: absent
  when: git_standup.stat.exists == False
  tags:
    - install_git_standup
