---
# @see https://flathub.org/apps/details/com.slack.Slack
- name: Install Slack
  become: yes
  flatpak:
    name: com.slack.Slack
    state: present
    method: system
  when: install_slack | default(false)
  tags:
    - install_slack
    - flatpak
