---
- name: Install graphical apps
  become: yes
  dnf:
    name: "{{ graphical_apps | default([]) }}"
    state: present
  tags:
    - install_graphical_apps

- name: Join wireshark group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: wireshark
    append: yes
  when: "'wireshark' in graphical_apps | default([])"
  tags:
    - install_graphical_apps
