---
- name: Install mkchromecast deps
  become: yes
  dnf:
    name: [
      "ffmpeg",
    ]
    state: present
  when: install_chromecast_audio
  tags:
    - install_chromecast_audio

- name: Download mkchromecast sources
  become: yes
  unarchive:
    src: "https://github.com/muammar/mkchromecast/archive/{{ mkchromecast_commit }}.zip"
    dest: "/usr/local/src"
    remote_src: yes
  register: mkchromecast_downloaded
  when: install_chromecast_audio
  tags:
    - install_chromecast_audio

- name: Install mkchromecast python deps
  become: yes
  pip:
    chdir: "/usr/local/src/mkchromecast-{{ mkchromecast_commit }}"
    requirements: "requirements.txt"
  when: install_chromecast_audio and mkchromecast_downloaded is changed
  tags:
    - install_chromecast_audio

- name: Build mkchromecast package
  become: yes
  command: "python setup.py build"
  args:
    warn: no
    chdir: "/usr/local/src/mkchromecast-{{ mkchromecast_commit }}"
  when: install_chromecast_audio and mkchromecast_downloaded is changed
  tags:
    - install_chromecast_audio

- name: Install mkchromecast package
  become: yes
  command: "python setup.py install"
  args:
    warn: no
    chdir: "/usr/local/src/mkchromecast-{{ mkchromecast_commit }}"
  when: install_chromecast_audio and mkchromecast_downloaded is changed
  tags:
    - install_chromecast_audio

# As pulseaudio starts in userland, do not use systemd but desktop session
# instead to start pulseaudio-dlna
- name: Autostart mkchromecast
  copy:
    src: .config/autostart/mkchromecast.desktop
    dest: ~/.config/autostart/mkchromecast.desktop
  when: install_chromecast_audio and autostart_chromecast_audio
  tags:
    - install_chromecast_audio
    - copy_mkchromecast_config
