---
- name: Check if nvim plugin manager is already installed
  stat:
    path: ~/.local/share/nvim/site/autoload/plug.vim
  register: plug
  tags:
    - configure_nvim

- name: Install nvim plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
  when: plug.stat.exists == False
  tags:
    - configure_nvim

- name: Upgrade nvim plugin manager
  shell: nvim +PlugUpgrade +qall
  tags:
    - configure_nvim

- name: Upgrade nvim plugins
  shell: nvim +PlugUpdate +qall
  tags:
    - configure_nvim

- name: Upgrade nvim remote plugins
  shell: nvim +UpdateRemotePlugins +qall
  tags:
    - configure_nvim
